services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    volumes:
      - .:/app

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
